### ISSUE TITLE
mysql entities for greek language

### ISSUE THREAD

**Issue by getit0** [imikado/mkframework#4]
Hello!
Trying to translate framework in Greek Language
Mk is fantastic!
When I store data in mysql tables I get these letters for greek (τα)
& tau ; & alpha ;
I think it is about json encode or html entities. I tried utf8mb4_general_ci and utf8_general_ci, for my database, utf-8 for site settings but nothing...
How I can use MK for Greek language?
Thank you

**Comment by imikado** [comment]
Hi,
You can change the charset used in the config file: conf/site.ini.php

[encodage]
;indique l'encodage des fichiers de code, utilise pour la protection des tableaux de contexte ($_GET,$_POST)
charset=UTF-8

**Comment by getit0** [comment]
Hello
I already done this, but no luck

this is my test table
Table structure for table `persons`
--

CREATE TABLE IF NOT EXISTS `persons` (
  `PersonID` int(11) NOT NULL DEFAULT '0',
  `LastName` varchar(255) DEFAULT NULL,
  `FirstName` varchar(255) DEFAULT NULL,
  `Address` varchar(255) DEFAULT NULL,
  `City` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PersonID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `persons`
--

INSERT INTO `persons` (`PersonID`, `LastName`, `FirstName`, `Address`, `City`) VALUES
(0, '&zeta;&delta;&delta;&phi;', 'sss', 'aaa 3', 'ff'),
(2, 'sdfsd', 'sdf', 's', 's');

so values (0, '& zeta ;& delta ;& delta ;& ph i;', 'sss', 'aaa 3', 'ff'), are greek characters. They appear right in view, but in database are stored as entities
http://www.htmlhelp.com/reference/html40/entities/symbols.html

**Comment by imikado** [comment]
I didn't anderstand that your values in your database was in greek

because the mkframework encode all caracters in html in database (for a security question)

You can tell in your pdo connexion your charset by adding ";charset=UTF-8" in your connexion.ini.php , the dsn field

for example:

mySqlConfig.dsn="mysql:dbname=myDatabase;host=localhost;charset=UTF-8"

**Comment by getit0** [comment]
I tried this before but still I don't resolve it...
The connection string accept
charset=utf8.
Could you please give me a working example to downlad and test?
Thank you for your help!
I need your framework to get rid of brand names... like yii and laravel...


Στις Παρασκευή, 4 Ιανουαρίου 2019, ο χρήστης Mika <notifications@github.com>
έγραψε:
> I didn't anderstand that your values in your database was in greek
>
> because the mkframework encode all caracters in html in database (for a
security question)
>
> You can tell in your pdo connexion your charset by adding
";charset=UTF-8" in your connexion.ini.php , the dsn field
>
> for example:
>
> mySqlConfig.dsn="mysql:dbname=myDatabase;host=localhost;charset=UTF-8"
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/4Rfd8JtNrUD1YVXSfddSyaKxxdW48SlqD0gIb6XQPekRbKVHw3ruZO4CnHrCsH1qWu6YoV9BKbsEJbK5yquaybxnQI22moV7xkD8LAbnj_Rr3Yrd2dOBdtgplaibw5IpN3ruZ-alqHPzTuGW-uzG7NpOJA=s0-d-e1-ft#https://github.com/notifications/beacon/AVuJkfmWgmkv8XlUDnAeMa3OsmU_9kDBks5u_1_lgaJpZM4Zn8dW.gif>

**Comment by imikado** [comment]
I try last minute
I only generate model couch and then generate a crud

this is my connexion file:

[db]
 
pdoMysqlExple.dsn="mysql:dbname=githubGreek;host=localhost;charset=UTF8"
pdoMysqlExple.sgbd=pdo_mysql
pdoMysqlExple.username=root
pdoMysqlExple.password=XXXX

And its works: the application show good caracters

This is my screenshot
https://imgur.com/a/xWAzkGc

**Comment by imikado** [comment]
If you want to disable this encode/decode in html you can set the 
[security]
xss.enabled=1

this is the parameter witch enable/disable encode/decode html to prenvent you a xss risk (this is why mk encode html in database)

**Comment by getit0** [comment]
BINGO!
it worked! It was xss.enabled=1 that made the difference.
Ok, for new databases and projects, I will use xss enabled

Thank you for your help!
**Mk framework is superb for fast and easy CRUD applications. Easy many2many relationships through framework, external pivot tables as combo box, alternative on the fly combo box from js array, CRUD grid view, multiline CRUD view like excel! batch update, fast and easy ORM, acl, auth modules. External modular design for each project (DDD). Mvc and CMF ready! IDE included through web app. Exported code works ootb in its app folder place! Bootstrap compatible**

**Comment by imikado** [comment]
Yes the mkframework is not a CMS, the builder only help you to create starter module to make your development easier

That's why you need to remove and regenerate your CRUD module if you add/remove a field
The idea is to generate once, and then update files depending the modification you make
And to improve the page design ;)

If you want a dynamic list field, you can modify the crud provided by builder and modify loops foreach to get source in a variable config file for example

If you need more help, i invite you to post in dedicated forum made for this here: https://www.developpez.net/forums/f1355/applications/projets/projets-heberges/mkframework/

Your questions can help others users of the framework

One question: how did you know mkframework ? ( i only write articles/tutorials in french website/magazines) ?

**Comment by getit0** [comment]
Thank you Mika for your fast replies and invitation!
I found Mk trying almost every php framework exists...
Yes it is difficult to me understand French. I speak and read  a little
comci-comca :)
Ok, I will be in contact. I plan my new projects to develop through MK!
Nice to meet you :)

Στις Σάβ, 5 Ιαν 2019 στις 3:36 μ.μ., ο/η Mika <notifications@github.com>
έγραψε:
